### ISSUE TITLE
RDM responder test "server error" when max personality is 255

### ISSUE THREAD

**Issue by majcit** [OpenLightingProject/ola#1508]
I encountered an issue during OLA responder test,

my device is RGB LED fixture,
I planned to use all 255 different personalities, (1 DMX mode, 254 DEMO mode)

when I run the OLA responder test with 255 personalities, "server error" occures.
when I reduce personality to 254 (1 DMX, 253 DEMO) test passes sucessfully

according to 10.6.1, personality may be 1-255
so I think this "server error" is related to OLA.
![ola - server error](https://user-images.githubusercontent.com/44608221/47722621-7f428280-dc5b-11e8-93f5-d8b1f9db90f0.png)

**Comment by peternewman** [comment]
Hi @majcit ,

I assume this is also you:
http://www.rdmprotocol.org/forums/showthread.php?p=3223

Sorry, I saw and fixed a bug related to this, but hadn't had a chance to reply yet.

My fix is here:
https://github.com/OpenLightingProject/ola/commit/eb7ff0d02e4f7b2b4fc53863787f38231b486cf2

However that isn't the resolution to the error you're getting. What version of OLA are you running on what OS and how did you install it?

I think this is the fix for the bug you reported (but I'd still expect it should be fixed in any recent OS):
https://github.com/OpenLightingProject/ola/commit/e44415adbd72415daa8f2c310e4084fc6d1cf345

**Comment by peternewman** [comment]
That's a version of Linux released in 2016:
https://www.debian.org/News/2016/2016060402

You can find your Ola version at http://<ip of your server>:9090/

Apologies, those docs, like a number of our installation ones, could do with an update. Nowadays you're better following the normal steps to install the latest Raspbian:
https://projects.raspberrypi.org/en/projects/raspberry-pi-getting-started

Then just run:
`sudo apt-get install ola-rdm-tests`

You could in theory update Raspbian, but starting from scratch will be easier. If you've got another SD card, you can do the new stuff on the second card, so you've even got something to fall back on if you have an issue for some reason.

**Comment by majcit** [comment]
ok,
my old OLA version was 0.9.5

I just installed the latest Raspbian and ola-rdm-test. just as you said, very easy thanks so much.
my new Raspbian Ver : 9.4 (stretch)
my new OLA Ver : 0.10.3 

now [http://10.1.1.12:9090/ola.html](url) works fine , I can do discovery and send dmx data to my LED fixture successfully.

but, [http://10.1.1.12:9099/static/rdmtests.html](url) does not work :/
my browser (Chrome) displays access error  "ERR_CONNECTION_REFUSED"

did I miss something?

**Comment by peternewman** [comment]
Excellent, glad to hear it!

Did you run the OLAd process manually, or was it just working when you browsed to the address?

If you run `sudo /etc/init.d/rdm_test_server start` on the Pi, then 9099 should work.

This should make it start up automatically each time you restart the Pi:
`sudo update-rc.d rdm_test_server defaults`

**Comment by majcit** [comment]
I executed your last commands : 
![rdm_test_server - start](https://user-images.githubusercontent.com/44608221/47790124-0efd3500-dd1f-11e8-8471-b349a4a4fc76.png)


9090 works fine, I suspect All IP numbers are 0, but I can discover and change personality of LED fixture, and turn on LEDs using DMX CONSOLE successfully : 
![9090](https://user-images.githubusercontent.com/44608221/47790209-3ce27980-dd1f-11e8-9386-e46a95740a30.png)


9091 not work at all : 
![9099 - start](https://user-images.githubusercontent.com/44608221/47790246-55eb2a80-dd1f-11e8-9dd2-dcd1fe48c13d.png)

**Comment by peternewman** [comment]
What does `dpkg -l | grep -i ola` show?

What about `sudo /etc/init.d/rdm_test_server status`?

This feels like some of the packaging bugs that @yoe fixed haven't made it into Raspbian yet possibly.

**Comment by peternewman** [comment]
> 9090 works fine, I suspect All IP numbers are 0, but I can discover and change personality of LED fixture, and turn on LEDs using DMX CONSOLE successfully :

That's a bit odd. If you do `sudo /etc/init.d/olad restart` they'll probably show the right IPs.

**Comment by yoe** [comment]
On Wed, Oct 31, 2018 at 02:04:48PM +0000, Peter Newman wrote:
> This feels like some of the packaging bugs that @yoe fixed haven't made it into
> Raspbian yet possibly.

That's certainly possible. Fixing things in Debian stable (from which
Raspbian pulls) isn't done automatically.

If you think I should push an update to stable because something is
critically broken there, that can be done. But if there's a known
workaround that we can point people to, that's easier to get through the
red tape ;-)

-- 
To the thief who stole my anti-depressants: I hope you're happy

  -- seen somewhere on the Internet on a photo of a billboard

**Comment by majcit** [comment]
ok, after `dpkg -l | grep -i ola`
![dkpg](https://user-images.githubusercontent.com/44608221/47794427-1aedf480-dd29-11e8-8201-0cd80826ebfc.png)

after `sudo /etc/init.d/rdm_test_server status`
![status](https://user-images.githubusercontent.com/44608221/47794450-280ae380-dd29-11e8-9bcb-41c9462833c7.png)

after, `sudo /etc/init.d/olad restart` : 
9090 shows proper IP and works fine as before , 9091 opens but not work: 
![9090 - 1](https://user-images.githubusercontent.com/44608221/47794507-4d97ed00-dd29-11e8-8e30-68413d51fe24.png)

**Comment by peternewman** [comment]
Can we see the browser console error log for the failing page please @majcit ?

@yoe so that appears to be the same version as Debian, I'd hope it's working in stable there, but I don't know for certain.

**Comment by majcit** [comment]
there is no error message, 

9091 not opens at all before `rdm_test_server.py` , 
there is "ERR_CONNECTION_REFUSED" message on browser, 
there is no message on prompt

9091 opens after `rdm_test_server.py` but not work , 
there is no error message

I hope I understand right the meaning of "error log" as you expected, if not please forgive my poor knowlegde about LINUX !

command prompt log is here : 
`pi@raspberrypi:~ $ rdm_test_server.py
Checking olad status
Running RDM Tests Server on 127.0.0.1:9099
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/rdmtests.html HTTP/1.1" 200 15619
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/jquery-ui-1.8.21.custom.css HTTP/1.1" 200 33311
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/ui.multiselect.css HTTP/1.1" 200 1886
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/jquery.min.js HTTP/1.1" 200 135993
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/jquery-ui.custom.min.js HTTP/1.1" 404 0
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/ui.multiselect.js HTTP/1.1" 200 11024
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/rdm_tests.js HTTP/1.1" 200 29800
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/images/logo.png HTTP/1.1" 200 1579
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/images/discovery.png HTTP/1.1" 200 860
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/jquery-ui.custom.min.js HTTP/1.1" 404 0
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/images/external.png HTTP/1.1" 200 165
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /favicon.ico HTTP/1.1" 301 0
10.1.0.158 - - [31/Oct/2018 17:58:23] "GET /static/images/favicon.ico HTTP/1.1" 200 1406`

**Comment by yoe** [comment]
The `rdm_test_server status` thing shows that it's not actually running. It says `active (exited)`, which is due to the fact that sysv support in systemd is not entirely complete.

This is indeed due to the bug in [Debian](https://bugs.debian.org/876251). I'll see if I can push an update for that; it's pretty stupid.

Meanwhile, you can edit `/etc/init.d/rdm_test_server` and fix the `DAEMON_ARGS` line, like the bug report says, then restart it. That should fix it.

**Comment by peternewman** [comment]
> I hope I understand right the meaning of "error log" as you expected, if not please forgive my poor knowlegde about LINUX !

I was actually meaning within your web browser you should be able to run diagnostic tools or similar and see a console or error log there, however your log had given enough to go on.

> 
> is 127.0.0.1:9099 normal at first line above ?
> whille my OLA home is 10.1.1.12:9090 and I expect OLA rdm tester to be 10.1.1.12:9099
> 
> > Running RDM Tests Server on 127.0.0.1:9099

Yes, that's intended, we actually bind to 0.0.0.0, so you can access it from any IPs your machine has (e.g. WiFi and wired), but that doesn't make much sense to report, so instead we display the localhost address.

**Comment by peternewman** [comment]
> The `rdm_test_server status` thing shows that it's not actually running. It says `active (exited)`, which is due to the fact that sysv support in systemd is not entirely complete.
> 
> This is indeed due to the bug in [Debian](https://bugs.debian.org/876251). I'll see if I can push an update for that; it's pretty stupid.

That will fix it not starting from the init script @yoe although he's also running it manually which is serving up pages but still not working.

However this log line is the key:
`[31/Oct/2018 17:58:23] "GET /static/jquery-ui.custom.min.js HTTP/1.1" 404 0 10.1.0.158 - - `

I think this is another consequence of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760414 and Debian policy. Specifically https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790886 , it looks like in both Stretch and Sid, the symlink is from /usr/share/ola/rdm-server/jquery-ui.min.js, but the HTML has only had the version stripped off, not the custom bit (which presumably hopefully just optimised it/removed stuff not being used in that GUI).

I don't know how long a release cycle takes for you, but stretch is a no brainer I'd hope. However I'm hoping to release 0.10.8 imminently (I just need to do the NEWS, although I may add the other spelling of writeable too as I'd promised before), so it might possibly make sense to wait a bit for whichever one a new release would appear in.

You should be able to test the test server functionality on a test box by patching the dummy plugin to a universe and then running the test server against one of our dummy responders (they should pass all the tests of course!).

**Comment by majcit** [comment]
I installed an older version of Raspbian V9 : 
```
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

no succeed :/
9090 works fine, 
9091 open page but not work (not open UNIVERSE combo box nor RDM Responder combo box)

> You should be able to test the test server functionality on a test box by patching the dummy plugin to a universe and then running the test server against one of our dummy responders (they should pass all the tests of course!).

**for Enttec Usb Pro Device :** 
```
pi@raspberrypi:~ $ rdm_test_server.py
Checking olad status
Running RDM Tests Server on 127.0.0.1:9099
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/rdmtests.html HTTP/1.1" 200 15619
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/jquery-ui-1.8.21.custom.css HTTP/1.1" 200 33311
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/ui.multiselect.css HTTP/1.1" 200 1886
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/jquery.min.js HTTP/1.1" 200 135993
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/jquery-ui.custom.min.js HTTP/1.1" 404 0
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/ui.multiselect.js HTTP/1.1" 200 11024
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/rdm_tests.js HTTP/1.1" 200 29800
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/images/logo.png HTTP/1.1" 200 1579
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/images/discovery.png HTTP/1.1" 200 860
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/jquery-ui.custom.min.js HTTP/1.1" 404 0
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/images/external.png HTTP/1.1" 200 165
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /favicon.ico HTTP/1.1" 301 0
10.1.0.158 - - [01/Nov/2018 07:36:46] "GET /static/images/favicon.ico HTTP/1.1" 200 1406
```


**for Dummy Device :** 
```
pi@raspberrypi:~ $ rdm_test_server.py
Checking olad status
Running RDM Tests Server on 127.0.0.1:9099
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/rdmtests.html HTTP/1.1" 200 15619
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/jquery-ui-1.8.21.custom.css HTTP/1.1" 200 33311
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/ui.multiselect.css HTTP/1.1" 200 1886
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/jquery.min.js HTTP/1.1" 200 135993
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/jquery-ui.custom.min.js HTTP/1.1" 404 0
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/ui.multiselect.js HTTP/1.1" 200 11024
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/rdm_tests.js HTTP/1.1" 200 29800
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/images/logo.png HTTP/1.1" 200 1579
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/images/discovery.png HTTP/1.1" 200 860
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/images/external.png HTTP/1.1" 200 165
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /favicon.ico HTTP/1.1" 301 0
10.1.0.158 - - [01/Nov/2018 07:40:04] "GET /static/images/favicon.ico HTTP/1.1" 200 1406
```

**Comment by peternewman** [comment]
> I installed an older version of Raspbian V9 :

Sorry @majcit that was directed at @yoe rather than you.

> > You should be able to test the test server functionality on a test box by patching the dummy plugin to a universe and then running the test server against one of our dummy responders (they should pass all the tests of course!).

As was that.

 If you go back to the latest version of Raspbian and edit `/usr/share/ola/rdm-server/rdmtests.html`, you should find `jquery-ui.custom.min.js` in that file; change it to `jquery-ui.min.js`, then it should start working as intended.

**Comment by majcit** [comment]
sadly I have to return back and content with OLA 0.9.5  till new release of OLA 0.10.8 

I should say binary package image [http://dl.openlighting.org/raspbian-ola-0.9.5.zip](url)
is very easy to use and practical to set up RDM test server.

I kindly request if possible please prepare similar method for new versions.

thank you so much
regards

**Comment by majcit** [comment]
> If you go back to the latest version of Raspbian and edit /usr/share/ola/rdm-server/rdmtests.html, you should find jquery-ui.custom.min.js in that file; change it to jquery-ui.min.js, then it should start working as intended.

I tried to run test over Dummy device, I did as following : 
setup the new Raspbian ver 9 and update it 
installed OLA ver 10.3
I have changed the "rdmtests.html" content as you said above

the result:
9090 works fine as before, on Enttec Usb Pro

9099 opens page, 
combo boxes works fine, I can select Dummy univers and devices.
I can select all 426 test 
but RUN TEST button does not work (shows reflex to click), but test does not start

```
pi@raspberrypi:~ $ rdm_test_server.py
Checking olad status
Running RDM Tests Server on 127.0.0.1:9099
10.1.0.165 - - [02/Nov/2018 09:27:27] "GET /static/rdmtests.html HTTP/1.1" 200 15612
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/jquery-ui-1.8.21.custom.css HTTP/1.1" 200 33311
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/ui.multiselect.css HTTP/1.1" 200 1886
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/jquery.min.js HTTP/1.1" 200 135993
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/jquery-ui.min.js HTTP/1.1" 200 312860
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/ui.multiselect.js HTTP/1.1" 200 11024
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/rdm_tests.js HTTP/1.1" 200 29800
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/logo.png HTTP/1.1" 200 1579
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/discovery.png HTTP/1.1" 200 860
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/external.png HTTP/1.1" 200 165
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/ui-bg_glass_60_eeeeee_1x400.png HTTP/1.1" 200 110
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/ui-bg_inset-hard_75_999999_1x100.png HTTP/1.1" 200 114
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/ui-bg_inset-soft_50_c9c9c9_1x100.png HTTP/1.1" 200 96
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/ui-bg_glass_35_dddddd_1x400.png HTTP/1.1" 200 109
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/ui-icons_999999_256x240.png HTTP/1.1" 200 4369
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /GetUnivInfo?_=1541140047691 HTTP/1.1" 200 79
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /GetTestDefs?c=0&_=1541140047692 HTTP/1.1" 200 11693
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /favicon.ico HTTP/1.1" 301 0
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /GetDevices?u=2&_=1541140047693 HTTP/1.1" 200 128
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/ui-icons_70b2e1_256x240.png HTTP/1.1" 200 4369
10.1.0.165 - - [02/Nov/2018 09:27:28] "GET /static/images/favicon.ico HTTP/1.1" 200 1406
10.1.0.165 - - [02/Nov/2018 09:27:37] "GET /static/images/ui-bg_glass_100_f8f8f8_1x400.png HTTP/1.1" 200 105
10.1.0.165 - - [02/Nov/2018 09:27:37] "GET /static/images/ui-icons_3383bb_256x240.png HTTP/1.1" 200 4369
```
![dummy](https://user-images.githubusercontent.com/44608221/47897191-5bf51e80-de79-11e8-972b-8105866afaa7.png)

**Comment by yoe** [comment]
FYI, I've just uploaded an update for ola in Debian stable that fixes these issues. It should be part of an upcoming point release. There is one planned for next weekend, but I believe I'm too late for that one already.

**Comment by majcit** [comment]
👍 
glad to hear, thanks. I can't wait to see it. 
Maybe I go to workplace tomorrow to test it. 

İs new update available for users (me) now? 
Or shall I wait the official release?

**Comment by yoe** [comment]
No, you need to wait until it is in Debian stable. You can check [the tracking bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912444) in the Debian bts to see when that's done; it will be marked as 'closed' when the updated package is included and available.

**Comment by yoe** [comment]
(also, if you're using Raspbian, you may need to wait until the update of Raspbian that includes it... Don't know what their exact policies on that subject are, but they're usually reasonably fast with that)

**Comment by yoe** [comment]
On Wed, Oct 31, 2018 at 07:52:10PM -0700, Peter Newman wrote:
> You should be able to test the test server functionality on a test box by
> patching the dummy plugin to a universe and then running the test server
> against one of our dummy responders (they should pass all the tests of
> course!).

Is this something we can do from the command line? If so, might make
sense to add that to an autopkgtest in the Debian package...

-- 
To the thief who stole my anti-depressants: I hope you're happy

  -- seen somewhere on the Internet on a photo of a billboard

**Comment by peternewman** [comment]
> I should say binary package image [http://dl.openlighting.org/raspbian-ola-0.9.5.zip](url)
> is very easy to use and practical to set up RDM test server.
> 
> I kindly request if possible please prepare similar method for new versions.

See here for discussion on updating those:
https://github.com/OpenLightingProject/ola/issues/1212

In short I'm going to prioritise writing code myself, but others are welcome to work on building Pi images and keeping them up to date.

**Comment by peternewman** [comment]
Please can we see the browser's console/error log @majcit ? E.g. developer tools. If you let us know which browser, we can give you some assistance. There will be some sort of Javascript error occurring when you click the button.

**Comment by majcit** [comment]
I use Chrome , Win7 , as I find instruction from internet , the error log file must be created in as below : 
cmd: `chrome --enable-logging --v=1`
in `C:\Program Files (x86)\Google\Chrome\Application`
but not created , then I tried to reach IE log file but not succeed yet, 

BTW I noticed when I changed `jquery-ui.custom.min.js` to `jquery-ui.min.js` the caption of the RUN button is also changed as below:

with original `jquery-ui.custom.min.js` : 
![image](https://user-images.githubusercontent.com/44608221/48255363-1dc9a300-e415-11e8-903f-5b97a3cdec43.png)

after change to  `jquery-ui.min.js` : 
![image](https://user-images.githubusercontent.com/44608221/48255397-389c1780-e415-11e8-8dfa-98539e9e429f.png)

**Comment by peternewman** [comment]
> I use Chrome , Win7 , as I find instruction from internet , the error log file must be created in as below :
> cmd: `chrome --enable-logging --v=1`
> in `C:\Program Files (x86)\Google\Chrome\Application`
> but not created , then I tried to reach IE log file but not succeed yet,

You want this one @majcit :
https://developers.google.com/web/tools/chrome-devtools/console/

Yes, the styling would be intentional and shows the JS is now loading.

**Comment by majcit** [comment]
ok , finally I learned how to open error log for Chrome.
It is just as simple as press "F12" then cick "console" ! :'(

and here is the error log when I press "RUN TEST" button : 

```
rdm_tests.js:774 Uncaught TypeError: $(...).size is not a function
at RDMTests.validate_form (rdm_tests.js:774)
at HTMLButtonElement.<anonymous> (rdm_tests.js:220)
at HTMLButtonElement.dispatch (jquery.min.js:3)
at HTMLButtonElement.elemData.handle (jquery.min.js:2)
```
This error occurs in both if I "add all" test items, also when I dont add any test item.

**Comment by peternewman** [comment]
Excellent, glad you've discovered the joys of the browser console log.

@majcit (and indeed @yoe ) these fixes should make it actually work with the later JQuery Debian provides:
https://github.com/OpenLightingProject/ola/pull/1324/files

**Comment by majcit** [comment]
thanks Peter ,
well the latest Raspbian just released yesterday , it seems long time for next release. 

maybe this is silly question but my big question is how other people use new versions of OLA rdm tester, since as I understand >the only< downloadable and working OLA is 0.9.5 
How does later versions next to 0.9.5 of OLA work (maybe 0.10.2, or 0.10.1 etc) ?

**Comment by yoe** [comment]
On Sun, Nov 11, 2018 at 08:21:55AM -0800, Peter Newman wrote:
>     I think I misunderstood the previous post that I have to wait till new
>     release of Raspbian.
> 
> You won't need to wait for a full Raspbian release, just for them to update
> from Debian and release an updated version of that package

Well, that does require a full Debian point release, which implies a
full new Raspbian release :-)

> (once @yoe
> incorporates these fixes and they make it into the relevant Debian release).
> Because these files are plain text and interpreted, you can just edit them now
> and the fixes will work, although if you reinstall it, you'll need to apply the
> same fixes.

Right.

-- 
To the thief who stole my anti-depressants: I hope you're happy

  -- seen somewhere on the Internet on a photo of a billboard

**Comment by peternewman** [comment]
> On Sun, Nov 11, 2018 at 08:21:55AM -0800, Peter Newman wrote: I think I misunderstood the previous post that I have to wait till new release of Raspbian. You won't need to wait for a full Raspbian release, just for them to update from Debian and release an updated version of that package
> Well, that does require a full Debian point release, which implies a full new Raspbian release :-)

Ah, I didn't realise that, I assumed the fixes just appeared when you release the package given the steady stream of updates I get offered on my normal machine (or is this confusion between you releasing a full new version to stable/unstable and a fix getting backported to an older release)?

> thanks for complete explanations. I suceeded updating both :
> https://github.com/OpenLightingProject/ola/pull/1324/files
> and
> [eb7ff0d](https://github.com/OpenLightingProject/ola/commit/eb7ff0d02e4f7b2b4fc53863787f38231b486cf2)

Excellent, glad you got it sorted.

> It works fine with dummy devices and my device when Max Personalities < 255
> glad to have the latest working rdm responder test package : )

This isn't the latest working package, it's fixes to make the latest deb package released for your OS function correctly.
 
> ```
> Server Error
> An error has occured: ''GetOutOfRangePersonalityDescription' object has no attribute 'LABEL''
> Traceback (most recent call last):
>   File "/usr/bin/rdm_test_server.py", line 274, in _RunTests
>     tests, device = runner.RunTests(test_filter, False, self._UpdateStats)
>   File "/usr/lib/python2.7/dist-packages/ola/testing/rdm/TestRunner.py", line 333, in RunTests
>     test.Run()
>   File "/usr/lib/python2.7/dist-packages/ola/testing/rdm/ResponderTest.py", line 255, in Run
>     super(ResponderTestFixture, self).Run()
>   File "/usr/lib/python2.7/dist-packages/ola/testing/rdm/ResponderTest.py", line 196, in Run
>     self.Test()
>   File "/usr/lib/python2.7/dist-packages/ola/testing/rdm/TestMixins.py", line 934, in Test
>     self.SetNotRun('All %s are supported' % self.LABEL)
> AttributeError: 'GetOutOfRangePersonalityDescription' object has no attribute 'LABEL'
> Please report this bug so it can be fixed. Clicking 'Report Bug' will open a new window and prompt you to sign in with your Google account. Only the information you see here will be sent.
> ```

Sorry about that @majcit . I probably only tested against our git master and then backported the fix, or possibly only tested the test you'd initially reported as failing. Our git master has had a bit of a rewrite in this area of tests, so it masked that issue, anyway this will fix that particular (and hopefully final) bug:
https://github.com/OpenLightingProject/ola/pull/1511

**Comment by majcit** [comment]
ok,
after #1511 it is fixed ! : )
thank you very much Peter. 

and maybe my last question : 
when I install a fresh ola RDM responder tester `sudo apt-get install ola-rdm-tests`
it gets V 0.10.3 for me but I see there is V0.10.7 in release list https://github.com/OpenLightingProject/ola/releases .
do I overlook somthing ?

**Comment by peternewman** [comment]
> ok,
> after #1511 it is fixed ! : )
> thank you very much Peter.

Excellent, glad to hear it!
 
> and maybe my last question :
> when I install a fresh ola RDM responder tester `sudo apt-get install ola-rdm-tests`
> it gets V 0.10.3 for me but I see there is V0.10.7 in release list https://github.com/OpenLightingProject/ola/releases .
> do I overlook somthing ?

What does `lsb_release -a` show for you? The OLA releases page is the versions as released by the Open Lighting Project, the OSes (in this case Debian/Raspbian) then need to do any packaging changes their end and release those versions (so when 0.10.8 comes out imminently, there will be a (hopefully short) delay before that gets into a version of Debian once @yoe has worked his magic. However they generally value stability over bleeding edge, so you'd probably need to wait for the next Debian/Raspbian release before 0.10.8 (or later) appears.

Alternatively you could compile from scratch, or make your own deb or switch to a different OS (e.g. Arch offers git versions: https://aur.archlinux.org/packages/ola-git/ ).

So I think I'm right in saying you're happy and this can be closed as far as you are concerned @majcit ?

@yoe I assume you'll track merging the outstanding bits to fix oldstable etc in Debian's PTS so you don't need this open either? I'll wait for #1511 to be merged before closing anyway.

**Comment by majcit** [comment]
> What does lsb_release -a show for you? 
```
pi@raspberrypiOLA:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
```

Thanks so much again. I will wait new release 0.10.8 : )

> So I think I'm right in saying you're happy and this can be closed as far as you are concerned @majcit ?

sure I am very happy , I learned new things during this thread. and I got much more than I expected.
I would like to summerize the solution for my later reference and maybe for other users: 

---------------------------------------------------------------------------
To setup RDM Responder Tester 0.10.3 on Raspberry Pi : 
---------------------------------------------------------------------------
1) download and flash latest Raspbian https://www.raspberrypi.org/downloads/raspbian/
2) root@raspberrypi:~#sudo apt-get update
3) root@raspberrypi:~#sudo apt-get upgrade
4) root@raspberrypi:~#sudo apt-get install ola-rdm-tests
5) patch : root@raspberrypi:~# cd /usr/share/ola/rdm-server/rdm_tests.js
https://github.com/OpenLightingProject/ola/pull/1324/files
6) patch : root@raspberrypi:~# cd /usr/lib/python2.7/dist-packages/ola/testing/rdm/TestDefinitions.py
https://github.com/OpenLightingProject/ola/commit/eb7ff0d02e4f7b2b4fc53863787f38231b486cf2
and
https://github.com/OpenLightingProject/ola/pull/1511/commits/dcd5f110760a1a3a384d0f39a4e4d7857e1d2bce
7) root@raspberrypi:~# sudo update-rc.d rdm_test_server defaults
---------------------------------------------------------------------------

many thanks to all establishers, engineers and developers of OLA. It is definitly a great tool.
